#!/usr/bin/env python3
"""
Generate examples/SAMPLE-OUTPUTS.md from examples/cadence/.

This file used to be hand-maintained and drifted: eight skills shipped with
worked examples that never made it into the document people are told to start
with. Generating it means that can't happen again — same reason RESULTS.md and
workspace/INDEX.md are generated.

Categories and their order come from CLAUDE.md's own skill list, so a skill
added to the brain shows up here without anyone remembering to add it.

  python3 tests/build_sample_outputs.py
  python3 tests/build_sample_outputs.py --check   # CI: fail if the file is stale
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
EX = os.path.join(ROOT, "examples", "cadence")
OUT = os.path.join(ROOT, "examples", "SAMPLE-OUTPUTS.md")

TIER_BADGE = {"quick": "⚡", "guided": "🧭", "campaign": "🗓"}


def categories():
    """(emoji+label, [skills]) in the order CLAUDE.md lists them."""
    brain = open(os.path.join(ROOT, "CLAUDE.md"), encoding="utf-8").read()
    m = re.search(r"^## The skills \(your toolkit\)(.*?)^Skills \*\*compose\*\*",
                  brain, re.S | re.M)
    body = m.group(1) if m else brain
    out = []
    for line in body.split("\n"):
        lm = re.match(r"^\*\*(.+?)\*\*\s*—\s*(.+)$", line.strip())
        if not lm:
            continue
        skills = re.findall(r"`([a-z0-9-]+)`", lm.group(2))
        if skills:
            out.append((lm.group(1), skills))
    return out


def tier_of(skill):
    p = os.path.join(ROOT, "skills", skill, "SKILL.md")
    if not os.path.isfile(p):
        return None
    m = re.search(r"^tier:\s*(\w+)$", open(p, encoding="utf-8").read(), re.M)
    return m.group(1) if m else None


def body_of(skill):
    """The example, minus its own title line and generator note."""
    p = os.path.join(EX, f"{skill}.md")
    if not os.path.isfile(p):
        return None
    t = open(p, encoding="utf-8").read()
    t = re.sub(r"^#\s+.*?—\s*worked example.*?\n", "", t, count=1, flags=re.M)
    return t.strip()


def render():
    cats = categories()
    have, missing = [], []
    for _, skills in cats:
        for s in skills:
            (have if os.path.isfile(os.path.join(EX, f"{s}.md")) else missing).append(s)

    L = [
        "# Product Manager OS — Worked Examples",
        "",
        "Every skill in the OS, run against one demo company — **Cadence** (B2B "
        "async-standup SaaS, ~$3M ARR, fixing week-2 retention, launching an \"AI "
        "Blocker Detector\") — in a defined **house style** (TL;DR-led, sentence-case "
        "headings, \"teams\" not \"customers\", 🟢🟡🔴 status). This is exactly what "
        "each skill produces.",
        "",
        f"_{len(have)} outputs. Generated by `tests/build_sample_outputs.py` — do not "
        "hand-edit._",
        "",
        f"Tier: {TIER_BADGE['quick']} quick · {TIER_BADGE['guided']} guided · "
        f"{TIER_BADGE['campaign']} campaign.",
        "",
        "## Contents",
        "",
    ]
    for label, skills in cats:
        shown = [s for s in skills if os.path.isfile(os.path.join(EX, f"{s}.md"))]
        if not shown:
            continue
        L.append(f"**{label}**  ")
        for s in shown:
            L.append(f"- {TIER_BADGE.get(tier_of(s), '')} [{s}](#{s})")
        L.append("")

    if missing:
        L += ["", f"_Not shown ({len(missing)}): "
                  + ", ".join(f"`{m}`" for m in missing)
                  + " — these don't produce a markdown artifact._", ""]

    for label, skills in cats:
        for s in skills:
            b = body_of(s)
            if b is None:
                continue
            L += ["", "---", "", f'<a id="{s}"></a>', "", b, ""]
    return "\n".join(L).rstrip() + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else ""
        if cur != text:
            print("::error::examples/SAMPLE-OUTPUTS.md is stale. Run "
                  "'python3 tests/build_sample_outputs.py' and commit the result.")
            sys.exit(1)
        print("SAMPLE-OUTPUTS.md is current")
        return
    open(OUT, "w", encoding="utf-8").write(text)
    n = text.count('<a id="')
    print(f"examples/SAMPLE-OUTPUTS.md regenerated — {n} outputs")


if __name__ == "__main__":
    main()
